### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by sunnysinghin** [burntime/atom-monokai#15] opened 2017-01-31 09:08 UTC
![image](https://cloud.githubusercontent.com/assets/16998920/22458504/cdf989f8-e7c2-11e6-9c2a-cded73aea30a.png)

**Comment by burntime** [comment] 2017-01-31 09:27
I will have a look.

Duplicate of #13

**Closed by burntime** 2017-01-31 09:27 UTC
Labels: bug, duplicate

**Comment by sunnysinghin** [comment] 2017-01-31 09:33
after update 0.18.0 to 0.19.0
