### ISSUE TITLE
Markdown almost no color.

### ISSUE THREAD

**Issue by gluons** [burntime/atom-monokai#16] opened 2017-02-11 11:34 UTC
```
Atom    : 1.14.1 (x64)
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
OS      : Windows 10 Pro (64 Bits)
```

**UI Theme:** One Dark

**Atom Monokai:**

![atom-monokai](https://cloud.githubusercontent.com/assets/4688092/22853405/02cb5ce2-f088-11e6-8628-2af399e7fd9d.PNG)

---

**One Dark:**

![one-dark](https://cloud.githubusercontent.com/assets/4688092/22853409/1995f842-f088-11e6-92e3-0ea75bb9d44e.PNG)

**Comment by burntime** [comment] 2017-02-14 08:38
Hey @gluons could you try to reinstall atom-monokai?

**Comment by burntime** [comment] 2017-02-14 08:40
Duplicate of #13

**Comment by gluons** [comment] 2017-02-14 09:36
@burntime Fresh installed Atom. Fresh installed `atom-monokai`.
> Because Atom recently release Windows 64bits version after [1.14.0](https://github.com/atom/atom/releases/tag/v1.14.0). So, I cleanly reinstall everything.

**Comment by burntime** [comment] 2017-02-14 10:19
Did you check other files then the markdown as well? Just realised that the markown is not styled that much yet.

![bildschirmfoto 2017-02-14 um 11 19 01](https://cloud.githubusercontent.com/assets/160396/22924934/4d49dc46-f2a7-11e6-8472-ee9a93dab0ea.png)
![bildschirmfoto 2017-02-14 um 11 18 32](https://cloud.githubusercontent.com/assets/160396/22924935/4d4a46f4-f2a7-11e6-8e55-3a038e757b47.png)

**Comment by burntime** [comment] 2017-02-14 10:24
Okay looks like I understood you wrong. Yes the markdown is not that colorful yet. I will add some colors soon. Also feel free to contribute if this is not fast enough.

**Comment by burntime** [comment] 2017-02-16 13:45
![bildschirmfoto 2017-02-16 um 14 44 11](https://cloud.githubusercontent.com/assets/160396/23023559/80ff5f2e-f456-11e6-8efa-f5103e13b753.png)

**Closed** 2017-02-16 13:45 UTC
Labels: enhancement
