### ISSUE TITLE
Deprecated selector in `atom-monokai\index.less`

### ISSUE THREAD

**Issue by nindiekindie** [burntime/atom-monokai#18] opened 2017-05-24 21:39 UTC
In `atom-monokai\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.tab-bar .tab,
.tab-bar .tab.active` => `.tab-bar .syntax--tab,
.tab-bar .syntax--tab.active`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

-----
I can open a PR if you want, too.

**Comment by burntime** [comment] 2017-06-21 09:06
HI @nindiekindie , this looks like a duplicate of https://github.com/burntime/atom-monokai/issues/12, did you found any deprecated selectors?

**Comment by nindiekindie** [comment] 2017-06-21 19:39
Yep, it's a duplicate - I'm sorry! There aren't any deprecated selectors anymore. Dunno why I didn't see issue 12 ... sorry again :/

**Closed** 2017-06-22 08:36 UTC
Labels: duplicate, enhancement
